apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rajverma1985/my-gitops-repo.git
    targetRevision: HEAD
    path: charts/guestbook
    helm:
      values: |
        replicaCount: 1
        service:
          type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: staging

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rajverma1985/my-gitops-repo.git
    targetRevision: HEAD
    path: charts/nginx
    helm:
      values: |
        replicaCount: 1
        service:
          type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
