# charts/guestbook/values.yaml
serviceAccount:
  create: true  # Explicitly define service account creation
  name: ""      # Empty defaults to chart name

image:
  repository: gcr.io/google-samples/gb-frontend
  tag: v4
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
