# apps/prometheus-operator/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- monitoring.coreos.com_alertmanagers.yaml
- monitoring.coreos.com_prometheuses.yaml
- monitoring.coreos.com_prometheusagents.yaml
- monitoring.coreos.com_thanosrulers.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"  # Ensures CRDs deploy first
