apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rajverma1985/my-gitops-repo.git
    targetRevision: HEAD
    path: charts/nginx
    helm:
      values: |
        replicaCount: 3
        service:
          type: LoadBalancer
          port: 80
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: false  # Manual sync for production
