apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
  - repoURL: https://github.com/rajverma1985/my-gitops-repo.git
    targetRevision: HEAD
    path: apps/prometheus-operator
    # CRDs will sync first due to wave annotation in their kustomization.yaml
  - repoURL: https://github.com/rajverma1985/my-gitops-repo.git
    targetRevision: HEAD
    path: environments/staging
    # Regular apps will sync after CRDs
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
