apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rajverma1985/my-gitops-repo.git
    targetRevision: HEAD
    path: charts/nginx
    helm:
      values: |
        replicaCount: 2
        service:
          type: NodePort
          port: 80
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
